CREATE TABLE IF NOT EXISTS "public"."tblRoles" (
    "RoleID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleName" TEXT NOT NULL UNIQUE
);
-- statement-break
CREATE TABLE IF NOT EXISTS "public"."tblPermissions" (
    "PermID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PermName" TEXT NOT NULL UNIQUE
);
-- statement-break
CREATE TABLE IF NOT EXISTS "public"."tblRolePermissions" (
    "RoleID" INTEGER NOT NULL REFERENCES "public"."tblRoles" ("RoleID") ON DELETE CASCADE,
    "PermID" INTEGER NOT NULL REFERENCES "public"."tblPermissions" ("PermID") ON DELETE CASCADE,
    PRIMARY KEY ("RoleID", "PermID")
);
-- statement-break
CREATE TABLE IF NOT EXISTS "public"."tblUserRoles" (
    "UserRoleID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NULL,
    "Idno" TEXT NULL,
    "RoleID" INTEGER NOT NULL REFERENCES "public"."tblRoles" ("RoleID") ON DELETE CASCADE,
    "AssignedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "chk_tblUserRoles_identity" CHECK (num_nonnulls("username", "Idno") = 1)
);
-- statement-break
CREATE UNIQUE INDEX IF NOT EXISTS "idx_tblUserRoles_username_role"
    ON "public"."tblUserRoles" ("username", "RoleID")
    WHERE "username" IS NOT NULL;
-- statement-break
CREATE UNIQUE INDEX IF NOT EXISTS "idx_tblUserRoles_idno_role"
    ON "public"."tblUserRoles" ("Idno", "RoleID")
    WHERE "Idno" IS NOT NULL;
-- statement-break
CREATE INDEX IF NOT EXISTS "idx_tblRolePermissions_roleid"
    ON "public"."tblRolePermissions" ("RoleID");
-- statement-break
CREATE INDEX IF NOT EXISTS "idx_tblRolePermissions_permid"
    ON "public"."tblRolePermissions" ("PermID");
-- statement-break
INSERT INTO "public"."tblRoles" ("RoleName")
VALUES
    ('Admin'),
    ('Librarian'),
    ('Patron')
ON CONFLICT ("RoleName") DO NOTHING;
-- statement-break
INSERT INTO "public"."tblPermissions" ("PermName")
VALUES
    ('catalog:read'),
    ('catalog:write'),
    ('catalog:delete'),
    ('patrons:read'),
    ('patrons:write'),
    ('patrons:delete'),
    ('circulation:read'),
    ('circulation:write'),
    ('authorities:write'),
    ('inventory:audit'),
    ('reservations:write'),
    ('reports:read'),
    ('settings:write'),
    ('system:import')
ON CONFLICT ("PermName") DO NOTHING;
-- statement-break
INSERT INTO "public"."tblRolePermissions" ("RoleID", "PermID")
SELECT roles."RoleID", perms."PermID"
FROM (
    VALUES
        ('Admin', 'catalog:read'),
        ('Admin', 'catalog:write'),
        ('Admin', 'catalog:delete'),
        ('Admin', 'patrons:read'),
        ('Admin', 'patrons:write'),
        ('Admin', 'patrons:delete'),
        ('Admin', 'circulation:read'),
        ('Admin', 'circulation:write'),
        ('Admin', 'authorities:write'),
        ('Admin', 'inventory:audit'),
        ('Admin', 'reservations:write'),
        ('Admin', 'reports:read'),
        ('Admin', 'settings:write'),
        ('Admin', 'system:import'),
        ('Librarian', 'catalog:read'),
        ('Librarian', 'catalog:write'),
        ('Librarian', 'patrons:read'),
        ('Librarian', 'patrons:write'),
        ('Librarian', 'circulation:read'),
        ('Librarian', 'circulation:write'),
        ('Librarian', 'authorities:write'),
        ('Librarian', 'inventory:audit'),
        ('Librarian', 'reservations:write'),
        ('Librarian', 'reports:read'),
        ('Patron', 'catalog:read'),
        ('Patron', 'reservations:write')
) AS seed("RoleName", "PermName")
INNER JOIN "public"."tblRoles" roles
    ON roles."RoleName" = seed."RoleName"
INNER JOIN "public"."tblPermissions" perms
    ON perms."PermName" = seed."PermName"
ON CONFLICT ("RoleID", "PermID") DO NOTHING;
-- statement-break
INSERT INTO "public"."tblUserRoles" ("Idno", "RoleID")
SELECT user_seed."Idno", role_seed."RoleID"
FROM "public"."tblUser" user_seed
INNER JOIN "public"."tblRoles" role_seed
    ON role_seed."RoleName" = 'Patron'
WHERE COALESCE(user_seed."Idno", '') <> ''
  AND NOT EXISTS (
      SELECT 1
      FROM "public"."tblUserRoles" existing
      WHERE existing."Idno" = user_seed."Idno"
        AND existing."RoleID" = role_seed."RoleID"
  );
-- statement-break
WITH role_ids AS (
    SELECT
        MAX(CASE WHEN "RoleName" = 'Admin' THEN "RoleID" END) AS admin_role_id,
        MAX(CASE WHEN "RoleName" = 'Librarian' THEN "RoleID" END) AS librarian_role_id,
        MAX(CASE WHEN "RoleName" = 'Patron' THEN "RoleID" END) AS patron_role_id
    FROM "public"."tblRoles"
)
INSERT INTO "public"."tblUserRoles" ("username", "RoleID")
SELECT
    password_seed."username",
    CASE
        WHEN LOWER(COALESCE(password_seed."usergroup", '')) = 'admin' THEN role_ids.admin_role_id
        WHEN LOWER(COALESCE(password_seed."usergroup", '')) IN ('catcirc', 'staff', 'librarian') THEN role_ids.librarian_role_id
        ELSE role_ids.patron_role_id
    END AS resolved_role_id
FROM "public"."tblPassword" password_seed
CROSS JOIN role_ids
WHERE COALESCE(password_seed."username", '') <> ''
  AND NOT EXISTS (
      SELECT 1
      FROM "public"."tblUserRoles" existing
      WHERE existing."username" = password_seed."username"
        AND existing."RoleID" = CASE
            WHEN LOWER(COALESCE(password_seed."usergroup", '')) = 'admin' THEN role_ids.admin_role_id
            WHEN LOWER(COALESCE(password_seed."usergroup", '')) IN ('catcirc', 'staff', 'librarian') THEN role_ids.librarian_role_id
            ELSE role_ids.patron_role_id
        END
  );
